### ISSUE TITLE
 F5 XC Health Checks are different from BIG-IP

### ISSUE THREAD

**Issue by Nikoolayy1** [Mikej81/bigip_to_xc_faq#2]
This post explains that to have similar behaviour like BIG-IP HTTP monitors the " Connection: Close " needs to be added to the XC monitors.

https://community.f5.com/discussions/distributedcloudusersforum-board/a-quick-post-on-how-f5-xc-health-checks-are-different-from-big-ip/312170

**Comment by Mikej81** [comment]
Connection-specific header fields such as [Connection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) and [Keep-Alive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive) are prohibited in [HTTP/2](https://httpwg.org/specs/rfc9113.html#ConnectionSpecific) and [HTTP/3](https://httpwg.org/specs/rfc9114.html#header-formatting). Chrome and Firefox ignore them in HTTP/2 responses, but Safari conforms to the HTTP/2 spec requirements and does not load any response that contains them.

So, is the ask to add the header in XC health checks when the upstream is a BIG-IP on HTTP/1.1?

**Comment by Nikoolayy1** [comment]
It for general HTTP1.1 upstream connection @Mikej81 not specific to BIG-IP.
